#!/bin/bash
if [ -n "$1" ]
then
  case "$1" in
    1) ./generator --flow-one > maps/--flow-one 2> /dev/null
      echo "--flow-one Complete!" 2> /dev/null
			  ;;
    2) ./generator --flow-ten > maps/--flow-ten 2> /dev/null
     echo "--flow-ten Complete!" 2> /dev/null
			  ;;
    3) ./generator --flow-thousand > maps/--flow-thousand 2> /dev/null
     echo "--flow-thousand Complete!" 2> /dev/null
		  	;;
    4) ./generator --big > maps/--big 2> /dev/null
      echo "--big Complete!" 2> /dev/null
			  ;;
    5) ./generator --big-superposition > maps/--big-superposition 2> /dev/null
      echo "--big-superposition Complete!" 2> /dev/null
			  ;;
		-help|help|-h|h|--help|Помогити)
		    echo "1 : generates an ant farm with distinctive path and [1] ant in it"
        echo "2 : generates an ant farm with distinctive path and approximately [10] ants in it"
        echo "3 : generates an ant farm with distinctive path and approximately [100] ants in it"
        echo "4 : generates a big map (approximately [1000] rooms) to test the time complexity"
        echo "5 : generates a big map with overlapping paths"
        ;;
    *)
      echo "WTF!? Use flag -> -help"
        ;;
  esac
else
echo "usage: ./map [option]"
echo "options:"
echo "          -help: to read the manual"
fi